apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jira-service
  description: "gRPC service for albums"
  tags:
    - java
    - grpc
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: spotify-portal-public-demo/jira-service
    jira.com/project-key: INSH
spec:
  type: service
  lifecycle: production
  owner: "group:default/content"
