apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: album-service-grpc
  description: "gRPC API for albums"
spec:
  type: grpc
  lifecycle: production
  owner: "group:default/content"
  definition:
    $text: ./src/main/proto/album.proto
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: album-service
  description: "gRPC service for albums"
  tags:
    - java
    - grpc
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: spotify-portal-public-demo/album-service
    sonarqube.org/project-key: spotify-portal-public-demo_album-service
    grafana/dashboard-selector: album-service
    grafana/alert-label-selector: service_name=album-service
    backstage.io/kubernetes-id: album-service
    backstage.io/kubernetes-namespace: album-service
    backstage.io/kubernetes-label-selector: app=album-service
spec:
  type: service
  lifecycle: production
  owner: "group:default/content"
  system: "system:default/metadata"
  providesApis:
    - album-service-grpc
  dependsOn:
    - resource:album-service-db
